[build]
  command = "npm run production"
  publish = "dist"

# Redirect old URLs
[[redirects]]
  from = "/blog"
  to = "https://timmmmy.blog/"
  force = true

[[redirects]]
  from = "/blog/feed.xml"
  to = "https://timmmmy.blog/feed/"
  force = true
  status = 301
